# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bitcoin Lab
email: hello@bictoinlab.io
description: > # this means to ignore newlines until "baseurl:"
  Bitcoin recipes
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bictoinlab.io" # the base hostname & protocol for your site
twitter_username: 1bitcoinlab
github_username:  bictoinlabio

# Build settings
markdown: kramdown
